### ISSUE TITLE
async inference , how to draw bbox on original frame？

### ISSUE THREAD

**Issue by dsp6414** [decemberpei/openvino-ncs2-python-samples#4]
in queue ,there are only blob_input, how can i get original frame? i want to draw bbox in original frame.

**Comment by dsp6414** [comment]
Can you give an example or some suggestions? i need your help.

**Comment by decemberpei** [comment]
it is very simple, you just take look at the code and do it yourself,

春笋 <notifications@github.com> 于 2020年8月10日周一 下午9:29写道：
